name: friday_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.19.2+1
  flutter_staggered_grid_view: ^0.3.2
  flutter_time_picker_spinner: ^1.0.6+1
  charts_flutter: ^0.9.0
  fl_chart: 0.10.0
  google_maps_flutter: ^1.0.6
  flutter_swiper: ^1.1.6
  requests: ^3.3.0

  flutter_riverpod: ^0.12.1
  image_picker: ^0.6.7+14

  credit_card_slider: ^1.0.1

  google_fonts: ^1.1.1

  country_list_pick: ^1.0.1+2

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/kyc/
    - assets/images/shopping/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf

  uses-material-design: true
